import { LegalPageLayout } from "@/components/legal-page-layout";

export default function PrivacyPage() {
  return (
    <LegalPageLayout title="Privacy Policy" lastUpdated="[date]">
      <section>
        <h2>1. Information we collect</h2>
        <p>
          We collect information you provide directly, such as your email address, name, and
          transaction details (deposits, withdrawals, investments). We also collect information
          generated by your use of the service, such as balances, activity logs, and login
          sessions.
        </p>
      </section>

      <section>
        <h2>2. How we use your information</h2>
        <p>
          We use your information to operate the service, process deposits and withdrawals,
          communicate with you (including transactional emails), detect fraud, and comply with
          legal obligations.
        </p>
      </section>

      <section>
        <h2>3. Data sharing</h2>
        <p>
          We don&apos;t sell your personal information. We may share it with service providers who
          help us operate (e.g. email delivery), or when required by law, regulation, or legal
          process.
        </p>
      </section>

      <section>
        <h2>4. Data security</h2>
        <p>
          We use industry-standard measures to protect your data, including encryption of
          sensitive fields at rest and in transit. No system is completely secure, and we
          can&apos;t guarantee absolute security.
        </p>
      </section>

      <section>
        <h2>5. Data retention</h2>
        <p>
          We retain financial records (transactions, deposits, withdrawals) as required for
          audit, dispute resolution, and legal compliance, even after an account is closed.
        </p>
      </section>

      <section>
        <h2>6. Your rights</h2>
        <p>
          Depending on your jurisdiction, you may have rights to access, correct, or request
          deletion of your personal information. Account deletion requests are reviewed by an
          admin; financial records are retained as described above even after account closure.
        </p>
      </section>

      <section>
        <h2>7. Cookies</h2>
        <p>
          We use essential cookies/local storage to keep you signed in and remember your
          preferences (like theme). We don&apos;t use third-party advertising trackers.
        </p>
      </section>

      <section>
        <h2>8. Children&apos;s privacy</h2>
        <p>This service is not intended for anyone under 18.</p>
      </section>

      <section>
        <h2>9. Changes to this policy</h2>
        <p>We may update this policy from time to time; material changes will be noted here.</p>
      </section>

      <section>
        <h2>10. Contact</h2>
        <p>Questions about this policy can be sent to [support email].</p>
      </section>
    </LegalPageLayout>
  );
}
