"use client";

import Link from "next/link";
import Image from "next/image";
import { useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import { AlertTriangle, ArrowUpRight, BarChart3, BriefcaseBusiness, CandlestickChart, ChartNoAxesCombined, Check, CircleCheck, FileCheck2, Landmark, ScanLine, ShieldCheck, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteHeader } from "@/components/marketing/site-header";
import { SiteFooter } from "@/components/marketing/site-footer";
import { TestimonialsSection } from "@/components/marketing/testimonials-section";
import { Skeleton } from "@/components/ui/skeleton";
import { MARKETING_IMAGES } from "@/lib/authImages";

const PRINCIPLES = [
  { icon: ScanLine, title: "Terms in plain sight", text: "Review the target rate, term, and payout style before you make a decision." },
  { icon: ShieldCheck, title: "Deliberate movement", text: "Every deposit and withdrawal is reviewed before it affects your account." },
  { icon: ChartNoAxesCombined, title: "A readable record", text: "Follow balances, investments, and activity from a single live dashboard." },
];
const STEPS = [
  { number: "01", title: "Open and verify", text: "Create your account and complete email verification before you access investment terms." },
  { number: "02", title: "Fund with clarity", text: "Choose a supported asset, send funds to the displayed address, and submit your request for review." },
  { number: "03", title: "Follow every move", text: "See balances, positions, payouts, and referrals in one live ledger as activity is recorded." },
];
const SERVICES = [
  { image: MARKETING_IMAGES.services.crypto, icon: CandlestickChart, title: "Crypto Market Investing", text: "Explore digital-asset market opportunities with strategy terms, asset selection, and account activity visible in one place." },
  { image: MARKETING_IMAGES.services.stocks, icon: BarChart3, title: "Stock Market Investing", text: "Build exposure to listed-market opportunities with an approach centered on research, position context, and long-term objectives." },
  { image: MARKETING_IMAGES.services.hedge, icon: BriefcaseBusiness, title: "Hedge Fund Management", text: "A disciplined investment-management approach designed to assess opportunities, manage exposure, and monitor strategy performance." },
  { image: MARKETING_IMAGES.services.portfolio, icon: Landmark, title: "Portfolio Management", text: "Bring allocations, investment activity, and portfolio context together so your capital is easier to understand and review." },
  { image: MARKETING_IMAGES.services.forex, icon: ChartNoAxesCombined, title: "Forex Trading", text: "Access foreign-exchange market strategies with clear visibility into your account activity and the terms of participation." },
];

export default function MarketingHomePage() {
  const plans = useQuery(api.investmentPlans.listPublic);
  return <div className="flex min-h-screen flex-col"><SiteHeader transparent /><main className="flex-1">
    <section className="relative isolate overflow-hidden bg-[#173824] text-white"><Image src={MARKETING_IMAGES.home} alt="City skyline behind bamboo foliage" fill priority sizes="100vw" className="-z-20 object-cover opacity-25" /><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_82%_35%,rgba(188,230,178,.22),transparent_24rem),linear-gradient(90deg,rgba(12,32,21,.98),rgba(23,56,36,.78),rgba(23,56,36,.40))]" /><div className="mx-auto grid min-h-[760px] max-w-7xl items-end gap-12 px-5 pb-16 pt-36 sm:px-8 sm:pb-20 lg:grid-cols-[1.15fr_.85fr]"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#bce6b2]">Deliberate digital-asset investing</p><h1 className="mt-6 max-w-4xl font-heading text-5xl font-semibold leading-[1.02] tracking-[-.055em] sm:text-7xl">A clearer place to put your capital to work.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/65">Fino brings investment terms, manual movement review, and a live account ledger into one composed experience.</p><div className="mt-10 flex flex-wrap gap-3"><Button size="lg" className="bg-[#bce6b2] text-[#173824] hover:bg-[#d9f3cf]" render={<Link href="/sign-up">Open an account <ArrowUpRight /></Link>} /><Button size="lg" variant="outline" className="border-white/20 bg-white/5 text-white hover:bg-white/10 hover:text-white" render={<Link href="/about">How Fino works</Link>} /></div></div><div className="rounded-[2rem] border border-white/15 bg-white/[.08] p-7 backdrop-blur-xl lg:mb-2"><p className="text-xs font-semibold uppercase tracking-[.2em] text-white/45">The Fino standard</p><div className="mt-7 space-y-5">{["Target terms displayed before commitment", "Manual review for funds movement", "Live activity and ledger visibility"].map((item) => <div key={item} className="flex gap-3 text-sm text-white/80"><span className="mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full bg-[#bce6b2] text-[#173824]"><Check className="size-3" /></span>{item}</div>)}</div><div className="mt-8 border-t border-white/10 pt-5 text-xs leading-5 text-white/45">Digital-asset investing carries risk. Target rates are not guarantees.</div></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.22em] text-primary">A calmer operating model</p><h2 className="mt-4 font-heading text-4xl font-semibold leading-[1.08] tracking-[-.045em] sm:text-5xl">Built to make investment mechanics easier to follow.</h2></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{PRINCIPLES.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-2xl border border-border/80 bg-card p-7"><div className="flex size-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5" /></div><h3 className="mt-6 font-heading text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></section>

    <section className="bg-[#173824] px-5 py-24 text-[#fbf7ed] sm:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.22em] text-[#bce6b2]">Investment services</p><h2 className="mt-4 font-heading text-4xl font-semibold leading-[1.08] tracking-[-.045em] sm:text-5xl">Market access, organized around a clearer view.</h2><p className="mt-5 text-sm leading-6 text-white/60">Fino brings a broad set of investment-focused services into one composed account experience.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{SERVICES.map(({ image, icon: Icon, title, text }) => <article key={title} className="group overflow-hidden rounded-2xl border border-white/10 bg-white/[.06]"><div className="relative h-48 overflow-hidden"><Image src={image} alt="Financial market analysis" fill sizes="(min-width: 1280px) 30vw, (min-width: 768px) 45vw, 100vw" className="object-cover opacity-75 transition-transform duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#173824] via-transparent to-transparent" /><span className="absolute bottom-4 left-5 flex size-10 items-center justify-center rounded-xl bg-[#bce6b2] text-[#173824]"><Icon className="size-5" /></span></div><div className="p-6"><h3 className="font-heading text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/60">{text}</p></div></article>)}</div><p className="mt-8 flex max-w-3xl gap-2 text-xs leading-5 text-white/45"><AlertTriangle className="size-4 shrink-0 text-[#d6a057]" />All investments involve risk, including possible loss of capital. Service availability and investment terms may vary by jurisdiction and account eligibility.</p></div></section>

    <section className="border-y border-border/70 bg-muted/45 px-5 py-24 sm:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-primary">A considered process</p><h2 className="mt-4 font-heading text-4xl font-semibold leading-[1.08] tracking-[-.045em]">From account opening to live ledger.</h2><p className="mt-5 max-w-sm text-sm leading-6 text-muted-foreground">Fino is structured around the moments that need clarity—not urgency or noise.</p><Button variant="outline" className="mt-7" render={<Link href="/faqs">Read common questions <ArrowUpRight /></Link>} /></div><div className="divide-y divide-border/70">{STEPS.map((step) => <div key={step.number} className="grid gap-4 py-6 sm:grid-cols-[72px_1fr]"><p className="font-heading text-2xl font-semibold text-primary/65">{step.number}</p><div><h3 className="text-lg font-semibold">{step.title}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-muted-foreground">{step.text}</p></div></div>)}</div></div></div></section>

    <section className="bg-[#f0f3eb] px-5 py-24 sm:px-8 dark:bg-[#1a3022]"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-3"><div className="lg:col-span-1"><p className="text-xs font-semibold uppercase tracking-[.22em] text-primary">Built around your account</p><h2 className="mt-4 font-heading text-4xl font-semibold leading-[1.08] tracking-[-.045em]">One place for the things you need to see.</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:col-span-2"><Feature icon={<WalletCards />} title="Wallet balances" text="Keep a clear view across supported assets and available funds." /><Feature icon={<FileCheck2 />} title="Account ledger" text="Trace deposits, investments, payouts, and rewards in one record." /><Feature icon={<ShieldCheck />} title="Reviewed requests" text="Submit deposits and withdrawals for deliberate administration review." /><Feature icon={<CircleCheck />} title="Referral rewards" text="See partner rewards alongside every other account movement." /></div></div></section>

    <section className="border-y border-border bg-muted/35 px-5 py-24 sm:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-primary">Available strategies</p><h2 className="mt-4 font-heading text-4xl font-semibold tracking-[-.045em]">Choose a plan with your eyes open.</h2></div><Button variant="outline" render={<Link href="/faqs">How plans work</Link>} /></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{plans === undefined ? Array.from({ length: 3 }).map((_, index) => <Skeleton key={index} className="h-80 rounded-2xl" />) : plans.length === 0 ? <p className="py-10 text-muted-foreground">New plans are being prepared. Create an account to stay in the loop.</p> : plans.map((plan) => <article key={plan._id} className="flex min-h-80 flex-col rounded-2xl border border-border/80 bg-card p-7"><div className="flex items-start justify-between"><h3 className="font-heading text-xl font-semibold">{plan.name}</h3><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">{plan.currency}</span></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{plan.description}</p><div className="mt-7 border-y border-border/70 py-5"><p className="font-heading text-4xl font-semibold">{(plan.rate * 100).toFixed(2)}%</p><p className="mt-1 text-xs text-muted-foreground">Target rate / {plan.rateInterval.replace("ly", "")}</p></div><div className="mt-5 flex flex-1 items-end justify-between text-sm"><span className="text-muted-foreground">From ${plan.minDepositUsd}</span><span>{plan.durationDays} days</span></div><p className="mt-5 flex gap-2 text-xs leading-5 text-muted-foreground"><AlertTriangle className="size-3.5 shrink-0 text-primary" />Target rates are not guaranteed.</p><Button className="mt-5 w-full" render={<Link href="/sign-up">Explore this plan</Link>} /></article>)}</div></div></section>
    <TestimonialsSection />
    <section className="mx-auto max-w-4xl px-5 py-24 text-center sm:px-8"><p className="text-xs font-semibold uppercase tracking-[.22em] text-primary">Start deliberately</p><h2 className="mt-4 font-heading text-4xl font-semibold tracking-[-.045em]">An account with less noise and more clarity.</h2><p className="mx-auto mt-5 max-w-xl text-muted-foreground">Open your account, verify your email, and explore the current investment terms before you fund anything.</p><Button size="lg" className="mt-8" render={<Link href="/sign-up">Create your account <ArrowUpRight /></Link>} /></section>
  </main><SiteFooter /></div>;
}

function Feature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <article className="rounded-2xl border border-border/70 bg-background/75 p-6"><span className="flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary">{icon}</span><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>; }
